version: '2.2'

services:
  crbs:
    build: ./crbs
    container_name: crbs
    restart: unless-stopped
    volumes:
      - app:/var/www/html/
    depends_on:
      - mariadb
    env_file:
      - default.env
  mariadb:
    image: mariadb:10
    container_name: crbs-mariadb
    restart: unless-stopped
    env_file:
      - default.env
    volumes:
      - db:/var/lib/mysql 
  arch:
    build: ./crbs-scripts
    container_name: crbs-scripts
    env_file:
      - default.env
    stdin_open: true
    tty: true

networks:
 default:
  external:
    name: letsencrypt

volumes:
  db:
  app:
