version: '3.3'

x-environment: &commonEnvironment
  MARIADB_ROOT_PASSWORD: securePassword123
  MARIADB_DATABASE: crbs_db
  MARIADB_USER: crbs_user
  MARIADB_PASSWORD: 6vTccw7zYF

services:
  crbs:
    build: ./crbs
    container_name: crbs
    restart: unless-stopped
    volumes:
      - app:/var/www/html/
    ports:
      - "8081:80"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10
    container_name: crbs-mariadb
    restart: unless-stopped
    expose:
      - 3306
    environment: *commonEnvironment
    volumes:
      - db:/var/lib/mysql 
  arch:
    build: ./crbs-scripts
    container_name: crbs-scripts
    environment: *commonEnvironment
    stdin_open: true
    tty: true

volumes:
  db:
  app:
